_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
architecture:
    value: LSTM
dataset:
    value: Flood Prediction
epochs:
    value: 20
