name: Python CI with Multi-OS, Multi-Python, and PyTorch Testing

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
        torch-version: ["1.13.1", "2.0.0"] # Replace with desired PyTorch versions

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Cache Python dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.torch-version }} torchvision -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      # Run linter (flake8 for example)
      - name: Run Linter
        run: |
          pip install flake8
          flake8 src/ tests/

      # Run tests
      - name: Run Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=src tests/

      # Pre-commit Hooks
      - name: Run Black
        run: |
          pip install black
          black src/ tests/
